<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'cc'
            };
            layout([
                {
                    component: 'Xendit_M2Invoice/js/view/payment/method-renderer/multishipping/cc',
                    name: 'payment_method_cc',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);

            if(window.checkoutConfig.payment[paymentMethodData.method].image.length > 0) {
                $(window.checkoutConfig.payment[paymentMethodData.method].image.reverse()).each(function(key, value){
                    $("label[for=p_method_"+paymentMethodData.method+"]")
                        .prepend("<img class='xendit-payment-icon' src="+value+">");
                });
            }

            $('body').trigger('contentUpdated');
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
