<?php

if ($block->getPaymentMethod() === 'cc_subscription') {
    $subscriptionData = $block->getSubscriptionConfig();
    $moreThan1 = ($subscriptionData['card_subscription_interval_count'] > 1 ? true : false);
?>
<div id="xendit-subscription-info" style="display: none;">
    <strong class="box-title">
        <span>Subscription Information</span>
    </strong>
    <div class="box-content">Every <?php
        if ($moreThan1) {
            echo $subscriptionData['card_subscription_interval_count'] . ' ';
        }
        echo strtolower($subscriptionData['card_subscription_interval']);
        if ($moreThan1) {
            echo 's';
        }
    ?></div>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        $(function () {
            var html = $('#xendit-subscription-info').html();
            $('.block-order-details-view .block-content').append('<div class="box box-order-subscription-info">' + html + '</div>');
        })
    })
</script>
<?php } ?>