<?php
/**
 * @var $block \Xendit\M2Invoice\Block\Checkout\Qrcode
 */
?>
<?php
$qrcodeImagePath = $block->getData('xendit_qrcode_path');
$externalId = $block->getData('xendit_qrcode_external_id');
$amount = $block->getData('xendit_qrcode_amount');
$isMultishipping = $block->getData('xendit_qrcode_is_multishipping') ? 1 : 0 ;
$statusUrl = $block->getUrl('xendit/checkout/qrcodecheckstatus');
$redirectUrl = $block->getUrl('xendit/checkout/qrcodesimulate');
?>
<?php if ($qrcodeImagePath): ?>
    <?php if ($block->isTestEnvironment()): ?>
        <div class="simulate">
            <form class="form qr-simulate"
                  action="<?= $block->escapeUrl($block->getQrcodeSimulateAction()) ?>"
                  id="simulate-form"
                  method="post">
                <input type="hidden" name="externalId" id="externalId" value="<?= $externalId ?>" />
                <input type="hidden" name="amount" id="amount" value="<?= $amount ?>" />
                <input type="hidden" name="isMultishipping" id="isMultishipping" value="<?= $isMultishipping ?>" />
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Simulate Qrcode Payment')) ?>" class="action submit primary">
                            <span><?= $block->escapeHtml(__('Simulate Qrcode Payment')) ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    <?php //else: ?>
        <script type="text/x-magento-init">
            {
                "body": {
                    "checkQrcodeStatus": {
                        "externalId":"<?= $externalId ?>",
                        "amount":"<?= $amount ?>",
                        "isMultishipping":"<?= $isMultishipping ?>",
                        "checkStatusUrl":"<?= $block->getUrl('xendit/checkout/qrcodecheckstatus') ?>",
                        "redirectUrl":"<?= $block->getUrl('xendit/checkout/qrcodesimulate') ?>"
                    }
                }
            }
        </script>
    <?php endif; ?>
    <div class="qrcode"><img src="<?= $qrcodeImagePath ?>"/></div>
    <div class="qrcode-data" data-check-status-url=<?= $statusUrl?> data-redirect-url=<?= $redirectUrl ?>
         data-is-multishipping="<?= $isMultishipping ?>" data-amount="<?= $amount  ?>" data-external-id="<?= $externalId ?>" />
<?php else: ?>
    <div class="qrcode-error"><?php echo "Error on generating Qrcode." ?></div>
<?php endif ?>
